---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.5.1
  amd64: ghcr.io/hassio-addons/debian-base:7.5.1
  armv7: ghcr.io/hassio-addons/debian-base:7.5.1
args:
  release: 1.41.1.9057-af5eaea7a
