---
build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base/aarch64:6.2.1
  amd64: ghcr.io/hassio-addons/ubuntu-base/amd64:6.2.1
  armv7: ghcr.io/hassio-addons/ubuntu-base/armv7:6.2.1
  i386: ghcr.io/hassio-addons/ubuntu-base/i386:6.2.1
args:
  release: 1.25.8.5663-e071c3d62
codenotary:
  signer: baris@ozdag.net
