---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.4.0
  amd64: ghcr.io/hassio-addons/debian-base:7.4.0
  armv7: ghcr.io/hassio-addons/debian-base:7.4.0
args:
  release: 1.41.0.8992-8463ad060
