---
build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base/aarch64:9.0.1
  amd64: ghcr.io/hassio-addons/ubuntu-base/amd64:9.0.1
  armv7: ghcr.io/hassio-addons/ubuntu-base/armv7:9.0.1
args:
  release: 1.32.8.7639-fb6452ebf
