---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.5.0
  amd64: ghcr.io/hassio-addons/debian-base:7.5.0
  armv7: ghcr.io/hassio-addons/debian-base:7.5.0
args:
  release: 1.41.0.8994-f2c27da23
