---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.8.1
  amd64: ghcr.io/hassio-addons/debian-base:7.8.1
  armv7: ghcr.io/hassio-addons/debian-base:7.8.1
args:
  release: 1.41.6.9685-d301f511a
