---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.3.3
  amd64: ghcr.io/hassio-addons/debian-base:7.3.3
  armv7: ghcr.io/hassio-addons/debian-base:7.3.3
args:
  release: 1.40.2.8395-c67dce28e
