---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.3.4
  amd64: ghcr.io/hassio-addons/debian-base:7.3.4
  armv7: ghcr.io/hassio-addons/debian-base:7.3.4
args:
  release: 1.40.2.8395-c67dce28e
