---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.8.3
  amd64: ghcr.io/hassio-addons/debian-base:7.8.3
  armv7: ghcr.io/hassio-addons/debian-base:7.8.3
args:
  release: 1.41.7.9799-5bce000f7
