---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.8.0
  amd64: ghcr.io/hassio-addons/debian-base:7.8.0
  armv7: ghcr.io/hassio-addons/debian-base:7.8.0
args:
  release: 1.41.5.9522-a96edc606
