---
build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base/aarch64:8.0.0
  amd64: ghcr.io/hassio-addons/ubuntu-base/amd64:8.0.0
  armv7: ghcr.io/hassio-addons/ubuntu-base/armv7:8.0.0
args:
  release: 1.29.0.6244-819d3678c
codenotary:
  base_image: codenotary@frenck.dev
  signer: baris@ozdag.net
