---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.3.1
  amd64: ghcr.io/hassio-addons/debian-base:7.3.1
  armv7: ghcr.io/hassio-addons/debian-base:7.3.1
args:
  release: 1.40.0.7998-c29d4c0c8
